### ISSUE TITLE
Invisible shop buttons can be pressed

### ISSUE THREAD

**Issue by NQNStudios** [Zolmeister/yummy-cupcake#3]
When there are too many buttons to fit in the shop window, the ones at the bottom are masked, but still receive input.

**Comment by Zolmeister** [comment]
https://github.com/Zolmeister/yummy-cupcake/blob/master/app/js/shop-state.js#L166

**Comment by NQNStudios** [comment]
Made worse because the hidden buttons actually overlap the "Back" button and steal its input events. Simply halting the hidden buttons' input events may not be enough to fix. Possible solution: check if input falls inside back button, manually trigger the event if necessary.
