### ISSUE TITLE
Score Loading Delay

### ISSUE THREAD

**Issue by NQNStudios** [Zolmeister/yummy-cupcake#5]
Possibly introduced by commit 7454079e41c7c725e9b04be0b363b110a3d283fd, or possibly previously unnoticed because of testing primarily in debug mode. 

When starting the game, the score appears as 0 but after a few seconds updates to reflect the player's actual saved score. Strangely, this also seems to cause inaccurate information to display in the shop.

**Comment by austinhallock** [comment]
This is probably because it takes some time for Clay data storage to grab the score - we could be smarter about how we load it

**Comment by NQNStudios** [comment]
I actually thought of this, but haven't yet had time to implement a fix. It seems I could simply delay the main state from opening until the save is loaded successfully (similar to the asynchronous loading of svgs though Promiz).

**Comment by austinhallock** [comment]
Yeah, that's probably the best option - to tack it in with the normal game load. It's loaded when line 257 on init.js is called.
